### PR TITLE
Added support for Docker-Compose

### PR DESCRIPTION
**Pull request by cron410**

### CODE REVIEW

**Comment by rackey12** [comment]
hi 
Thanks for this but can i have some help i am new to docker and have got a few working and think i under stand the process in the end i would like to make this apart of the compose file but i want to get it working first 

this is my code 
docker run -d --name rclone-mount \
    --restart=unless-stopped \
    --cap-add SYS_ADMIN \
    --device /dev/fuse \
    --security-opt apparmor:unconfined \
    -e RemotePath="tdrive:" \
    -e MountCommands="--allow-other --allow-non-empty" \
    -v /home/media/.config/rclone/rclone.conf:/config \
    -v /home/media/tdrive:/mnt/mediaefs:shared \
    mumiehub/rclone-mount

i have already downloaded and run rclone on my Ubuntu server and created the rclone.conf file to the google team drive the name given to this when doing the setup was tdrive

it is currently mounted to /home/media/tdrive using the following mount
sudo rclone --allow-non-empty --allow-other mount tdrive: /home/media/tdrive --size-only --dir-cache-time=2m --vfs-read-chunk-size=64M --vfs-cache-max-age 675h --vfs-read-chunk-size-limit=1G --buffer-size=32M

**Comment by Mumie-hub** [comment]
docker run -d --name rclone-mount
--restart=unless-stopped
--cap-add SYS_ADMIN
--device /dev/fuse
--security-opt apparmor:unconfined
-e RemotePath="tdrive:"
-e MountCommands="--allow-other --allow-non-empty --size-only --dir-cache-time=2m --vfs-read-chunk-size=64M --vfs-cache-max-age 675h --vfs-read-chunk-size-limit=1G --buffer-size=32M"
-v /home/media/.config/rclone/rclone.conf:/config/.rclone.conf
-v /home/media/tdrive:/mnt/mediaefs:shared
mumiehub/rclone-mount

should work.
When you mount a file inside the container (-v /home/media/.config/rclone/rclone.conf:/config/.rclone.conf) you have to specify an filename on the right also.
Your config file /home/media/.config/rclone/rclone.conf is not hidden?

**Comment by rackey12** [comment]
Thank you for the quick response no I don't believe the file is hidden I am able to browse to it and see the file. Should the rclone.conf have been created while in sudo su mode? Also to test can I mount it to a different folder e.g.-v /home/media/dtdrive:/mnt/mediaefs:shared

**Comment by Mumie-hub** [comment]
You can mount "anywhere" -v /mnt/test/tdrive:/mnt/mediaefs:shared
If you have a working rclone,conf you can mount it inside the container
/folder/rclone.conf:/config/.rclone.conf
The owner of the config file doesnt matter, because rclone runs as root inside the container.

**Comment by rackey12** [comment]
thank you so much for the help i though i had understood the command but just a few things that i did not understand 

if you don't mind could you check if my compose command is also correct
rclone:
    container_name: rclone
    image: mumiehub/rclone-mount
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    environment:
      - RemotePath="tdrive:"
      - MountCommands=--allow-other --allow-non-empty --size-only --dir-cache-time=2m --vfs-read-chunk-size=64M --vfs-cache-max-age 675h --vfs-read-chunk-size-limit=1G --buffer-size=32M
    volumes:
      - /home/media/.config/rclone/rclone.conf:/config/.rclone.conf
      - /home/media/dtdrive:/mnt/mediaefs:shared

thank you in advance.

**Comment by Mumie-hub** [comment]
Your Compose file should look something like this [pastebin](https://pastebin.com/TsjsiWCQ).
You can first test with privileged and than add devices, security_opt and cap_add.

**Comment by rackey12** [comment]
i have tried this and it creates the container but it crashes straight away with the following
Stopped for a few seconds with exit code 0

**Pull request closed without merging**
